# Enable extended keys (e.g. for apps that support Shift/Ctrl/Alt key combinations)
set -g allow-passthrough on
set -g extended-keys always
set -g terminal-features 'xterm*:clipboard:ccolour:cstyle:focus:title:extkeys,screen*:title,rxvt*:ignorefkeys'

# Cursor focus detection
set -g focus-events on

# Scrolling
set -g mouse on
